const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.BULL_PLAYWRIGHT_PATH || 'playwright');
const {registry, validateSection, resolveContent} = require('../apps/api/dist/cms/content.js');
const defaults = require('../apps/content/defaults.json');
const output = path.resolve(__dirname, '../artifacts/admin-v2');
const actor = {id:1,name:'Admin',role:'SUPER_ADMIN',cms_entered:true};
const dealer={id:1,name:'Tara Auto Hub Pvt. Ltd.',location:'Bihar',address:'Patna, Bihar',about:'Sales and service',active:true,domains:['tara.example.com']};
let drafts=[],writes=[];
const content=()=>resolveContent(drafts.map(d=>({...d,section_key:d.section_key}))).content;
(async()=>{
 fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 await context.addInitScript(user=>sessionStorage.setItem('bull-session',JSON.stringify({token:'ui-test',user})),actor);
 await context.route('**/api/**', async route=>{
  const req=route.request(), endpoint=new URL(req.url()).pathname;
  const reply=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
  if(endpoint==='/api/auth/me')return reply(actor);
  if(endpoint==='/api/site')return reply({dealer,products:content().products.items,mode:'cms',content:content(),sources:{}});
  if(endpoint==='/api/products')return reply(content().products.items);
  if(endpoint.endsWith('/registry'))return reply(registry());
  if(endpoint.endsWith('/dealers'))return reply([dealer]);
  if(endpoint.endsWith('/groups'))return reply([{id:11,name:'South region',dealerIds:[1]}]);
  if(endpoint.endsWith('/employees'))return reply([{id:1,name:'Arun',department:'Operations',active:true}]);
  if(endpoint.endsWith('/activity'))return reply([]);
  if(endpoint.endsWith('/media'))return reply(req.method()==='POST'?{url:'/admin/brand/bull-machine-logo.webp'}:[]);
  if(endpoint.endsWith('/resolved'))return reply({dealer,content:content(),sources:{}});
  if(endpoint.endsWith('/drafts')){
    if(req.method()==='GET')return reply(drafts);
    const body=req.postDataJSON();let document;
    try{document=validateSection(body.section,body.document);}catch(error){return reply({message:error.message},400);}
    writes.push(body);const saved={id:drafts.length+1,layer:body.layer,owner_id:body.ownerId,section_key:body.section,document,revision:body.expectedRevision+1,remove_override:body.removeOverride,published:true};
    drafts=[...drafts.filter(d=>d.layer!==saved.layer||d.owner_id!==saved.owner_id||d.section_key!==saved.section_key),saved];return reply(saved);
  }
  return reply({message:'Unexpected request '+endpoint},404);
 });
 await context.route('**/Asset/**',async route=>{
  const file=path.join(__dirname,'../apps/web/public',decodeURIComponent(new URL(route.request().url()).pathname));
  return fs.existsSync(file)?route.fulfill({path:file}):route.fulfill({status:404,body:''});
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const tab=name=>page.locator('.dealer-section-tabs').getByRole('button',{name,exact:true}).click();
 const save=async()=>{await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Changes published.',{exact:true}).waitFor();};
 try{
  await page.goto('http://127.0.0.1:5184/admin/dealers');
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).waitFor();
  assert.equal(await page.getByText('DEALER NETWORK',{exact:true}).count(),0);
  assert.equal(await page.getByRole('link',{name:'Common selection',exact:true}).count(),0);
  await page.screenshot({path:path.join(output,'dealers.png'),fullPage:true});
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).click();
  for(const name of ['Equipment','Gallery','Downloads','WhatsApp','Page layout','Dealer details','Dealer logo']) assert.equal(await page.locator('.dealer-section-tabs').getByRole('button',{name,exact:true}).count(),0);
  await page.getByLabel('Title',{exact:true}).fill('Tara — updated SEO');
  await page.getByLabel('Keywords',{exact:true}).fill('BULL, backhoe, Bihar');
  await page.getByLabel('Author',{exact:true}).fill('Tara Auto Hub');
  await save();
  await tab('Header');
  await page.locator('input[type=file]').waitFor();
  assert.equal(await page.locator('.section-editor input').count(),1);
  await save();assert.equal(writes.at(-1).section,'branding');
  await page.screenshot({path:path.join(output,'header.png')});
  await tab('Banners');
  assert.equal(await page.locator('.array-editor > details').count(),3);
  await page.locator('.array-editor summary').first().click();
  assert.equal(await page.getByLabel('Interval',{exact:true}).count(),0);
  assert.equal(await page.getByLabel('Scroll Label',{exact:true}).count(),0);
  assert.equal(await page.getByLabel('Link',{exact:true}).count(),0);
  assert.equal(await page.getByLabel('Alt',{exact:true}).count(),0);
  await save();
  await tab('Statistics');
  assert.equal(await page.locator('.array-editor > details').count(),4);
  assert.equal(await page.getByRole('button',{name:'+ Add item',exact:true}).count(),0);
  await page.locator('.array-editor summary').first().click();
  await page.getByLabel('Value',{exact:true}).first().fill('99+');await save();
  assert.equal(writes.at(-1).document.items.length,4);
  await tab('About us');
  assert.equal(await page.getByLabel('Button Label',{exact:true}).count(),0);
  assert.equal(await page.getByLabel('Button Link',{exact:true}).count(),0);
  await tab('Products');
  await page.getByLabel('Menu heading',{exact:true}).fill('Our machines');
  await save();
  await page.getByRole('button',{name:'Backhoe loaders',exact:true}).click();
  await page.getByLabel('Heading',{exact:true}).fill('BACKHOE\nPOWER');
  await page.getByLabel('Subtitle',{exact:true}).fill('Built for your work');
  await page.getByLabel('Description',{exact:true}).first().fill('Dealer-managed machine description.');
  page.once('dialog',dialog=>dialog.dismiss());
  await page.getByRole('button',{name:'Skid steers',exact:true}).click();
  assert.equal(await page.getByLabel('Heading',{exact:true}).inputValue(),'BACKHOE\nPOWER');
  await save();
  assert.equal(writes.at(-1).document.categories[0].heading,'BACKHOE\nPOWER');
  await page.locator('.item-thumbnail img').evaluateAll(images=>Promise.all(images.map(img=>img.decode().catch(()=>{}))));
  await page.screenshot({path:path.join(output,'products.png')});
  await page.getByRole('button',{name:'Skid steers',exact:true}).click();
  assert.equal(await page.locator('.array-editor > details').count(),2);
  await tab('Videos & testimonials');
  await page.locator('.array-editor summary').first().click();
  await page.getByLabel('Title',{exact:true}).first().fill('Customer story');
  await page.getByLabel('Description',{exact:true}).first().fill('Reliable performance for our team.');
  await page.getByLabel('YouTube video or embed link',{exact:true}).first().fill('<iframe src="https://www.youtube.com/embed/m2VSTjDi0nA"></iframe>');
  await save();assert.equal(writes.at(-1).document.items[0].videoId,'m2VSTjDi0nA');
  await page.screenshot({path:path.join(output,'testimonials.png')});
  await tab('Footer');
  await page.getByLabel('Name',{exact:true}).fill('Tara Footer Contact');
  await page.getByLabel('Address',{exact:true}).fill('Patna, Bihar');
  assert.equal(await page.getByLabel('Copyright',{exact:true}).count(),0);
  assert.equal(await page.locator('input[type=file]').count(),0);
  await save();assert.equal(writes.at(-1).section,'dealerContact');
  await page.getByRole('button',{name:'Follow us',exact:true}).click();
  await page.getByLabel('Enabled',{exact:true}).check();
  await page.locator('.array-editor summary').first().click();
  await page.getByLabel('Label',{exact:true}).fill('Instagram');
  await page.getByLabel('Link',{exact:true}).fill('https://www.instagram.com/example/');await save();
  await tab('Service');assert.equal(await page.getByLabel('Link',{exact:true}).count(),0);
  await tab('Contact');await page.getByRole('heading',{name:'Enquiry form',exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'contact.png')});
  await page.keyboard.press('Escape');
  await page.getByRole('link',{name:'Employees',exact:true}).click();
  await page.getByRole('heading',{name:'Employees',exact:true}).waitFor();
  assert.equal(await page.locator('.admin-shell .staff-embedded').count(),1);
  await page.getByRole('button',{name:'New Employee',exact:true}).click();
  await page.getByRole('dialog').filter({hasText:'Employee Name'}).waitFor();
  await page.getByRole('button',{name:'Close employee form'}).click();
  await page.screenshot({path:path.join(output,'employees.png'),fullPage:true});
  await page.goto('http://127.0.0.1:5184/admin/content');
  await page.locator('.section-card').first().waitFor();assert.equal(await page.locator('.section-card').count(),11);
  assert.equal(await page.getByText('WEBSITE CONTENT',{exact:true}).count(),0);
  const font=await page.locator('.section-card-meta').first().evaluate(el=>getComputedStyle(el).fontSize);assert.equal(font,'15px');
  await page.screenshot({path:path.join(output,'common.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:5184/admin/dealers');
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).click();await tab('Products');
  await page.getByRole('button',{name:'Backhoe loaders',exact:true}).click();
  await page.getByLabel('Heading',{exact:true}).waitFor();
  assert.equal(await page.getByRole('dialog').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);
  await page.screenshot({path:path.join(output,'mobile.png')});
  const headingTop=await page.locator('.cms-dialog-heading').evaluate(el=>el.getBoundingClientRect().top);
  const scrolling=await page.locator('.cms-dialog-body').evaluate(el=>{el.scrollTop=250;return {scroll:el.scrollTop,style:getComputedStyle(el).scrollbarWidth,color:getComputedStyle(el).scrollbarColor};});
  assert.ok(scrolling.scroll>0); assert.equal(scrolling.style,'thin'); assert.notEqual(scrolling.color,'auto');
  assert.equal(await page.locator('.cms-dialog-heading').evaluate(el=>el.getBoundingClientRect().top),headingTop);
  await page.screenshot({path:path.join(output,'popup-scroll.png')});
  const site=await context.newPage();site.on('pageerror',e=>errors.push(e.message));
  await site.goto('http://127.0.0.1:5183/');
  await site.getByRole('heading',{name:'BACKHOE POWER',exact:true}).waitFor();
  assert.equal(await site.title(),'Tara — updated SEO');
  assert.equal(await site.locator('meta[name=keywords]').getAttribute('content'),'BULL, backhoe, Bihar');
  assert.equal(await site.locator('.statistics .stat').count(),4);
  assert.equal(await site.locator('.dealer-about a').count(),0);
  assert.equal(await site.locator('.service-section a').count(),0);
  assert.equal(await site.locator('.banner-link').count(),0);
  assert.equal((await site.locator('.testimonial-description').first().innerText()).replace(/\s+/g,' ').trim(),'Customer story Reliable performance for our team.');
  assert.equal(await site.locator('.footer-contact strong').innerText(),'Tara Footer Contact');
  assert.equal(await site.locator('.footer-contact a[href="https://www.instagram.com/example/"]').count(),1);
  assert.equal((await site.locator('.products-menu-trigger').first().textContent()).trim(),'Our machines');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({result:'passed',checks:20,apiValidation:'real validateSection for every mocked save',liveDatabase:false,screenshots:8},null,2));
  console.log('PASS: v2 admin and public-site UI checks; real API schema validation applied to mocked saves.');
 } catch(error) { console.error("BROWSER ERRORS",errors); console.error((await page.locator("body").innerText()).slice(0,2000)); await page.screenshot({path:path.join(output,"failure.png")}); throw error; } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
