const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.BULL_PLAYWRIGHT_PATH || 'playwright');
const {registry, validateSection, resolveContent} = require('../apps/api/dist/cms/content.js');
const defaults = require('../apps/content/defaults.json');
const output = path.resolve(__dirname, '../artifacts/admin-v3');
const actor = {id:1,name:'Admin',role:'SUPER_ADMIN',cms_entered:true};
const dealer={id:1,name:'Tara Auto Hub Pvt. Ltd.',location:'Bihar',address:'Patna, Bihar',about:'Sales and service',active:true,domains:['tara.example.com']};
let drafts=[],writes=[];
const content=()=>resolveContent(drafts.map(d=>({...d,section_key:d.section_key}))).content;
(async()=>{
 fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 await context.addInitScript(user=>sessionStorage.setItem('bull-session',JSON.stringify({token:'ui-test',user})),actor);
 await context.route('**/api/**', async route=>{
  const req=route.request(), endpoint=new URL(req.url()).pathname;
  const reply=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
  if(endpoint==='/api/auth/me')return reply(actor);
  if(endpoint==='/api/site')return reply({dealer,products:content().products.items,mode:'cms',content:content(),sources:{}});
  if(endpoint==='/api/products')return reply(content().products.items);
  if(endpoint.endsWith('/registry'))return reply(registry());
  if(endpoint.endsWith('/dealers'))return reply([dealer]);
  if(endpoint.endsWith('/groups'))return reply([{id:11,name:'South region',dealerIds:[1]}]);
  if(endpoint.endsWith('/employees'))return reply([{id:1,name:'Arun',department:'Operations',active:true}]);
  if(endpoint.endsWith('/activity'))return reply([]);
  if(endpoint.endsWith('/media'))return reply(req.method()==='POST'?{url:'/admin/brand/bull-machine-logo.webp'}:[]);
  if(endpoint.endsWith('/resolved'))return reply({dealer,content:content(),sources:{}});
  if(endpoint.endsWith('/drafts')){
    if(req.method()==='GET')return reply(drafts);
    const body=req.postDataJSON();let document;
    try{document=validateSection(body.section,body.document);}catch(error){return reply({message:error.message},400);}
    writes.push(body);const saved={id:drafts.length+1,layer:body.layer,owner_id:body.ownerId,section_key:body.section,document,revision:body.expectedRevision+1,remove_override:body.removeOverride,published:true};
    drafts=[...drafts.filter(d=>d.layer!==saved.layer||d.owner_id!==saved.owner_id||d.section_key!==saved.section_key),saved];return reply(saved);
  }
  return reply({message:'Unexpected request '+endpoint},404);
 });
 await context.route('**/Asset/**',async route=>{
  const file=path.join(__dirname,'../apps/web/public',decodeURIComponent(new URL(route.request().url()).pathname));
  return fs.existsSync(file)?route.fulfill({path:file}):route.fulfill({status:404,body:''});
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const tab=name=>page.locator('.dealer-section-tabs').getByRole('button',{name,exact:true}).click();
 const save=async()=>{await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Changes published.',{exact:true}).waitFor();};
 try{
  await page.goto('http://127.0.0.1:5184/admin/dealers');
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).waitFor();
  for(const name of ['Media library','Publish center','Enquiries'])assert.equal(await page.getByRole('link',{name,exact:true}).count(),0);
  assert.equal(await page.locator('.dealers-page table').count(),0);
  assert.equal(await page.locator('.sidebar').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(36, 36, 36)');
  assert.equal(await page.locator('.sidebar').evaluate(el=>getComputedStyle(el,'::-webkit-scrollbar-button').display),'none');
  await page.screenshot({path:path.join(output,'dealers.png'),fullPage:true});
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).click();
  await page.getByLabel('Title',{exact:true}).fill('Tara equipment');
  await page.getByLabel('Social Title',{exact:true}).fill('Tara machines');
  await page.getByLabel('Site Name',{exact:true}).fill('Tara Auto Hub');
  assert.equal(await page.locator('.section-editor input[type=file]').count(),0);
  await save();
  await tab('Videos & testimonials');
  await page.locator('.content-list-item').first().click();
  let popup=page.getByRole('dialog').last();
  await popup.getByLabel('Title',{exact:true}).fill('Customer story');
  await popup.getByLabel('Description',{exact:true}).fill('Reliable performance.\nComfort for every working day.');
  await popup.getByLabel('YouTube video or embed link',{exact:true}).fill('https://youtu.be/m2VSTjDi0nA');
  await page.screenshot({path:path.join(output,'testimonial-edit.png')});
  await popup.getByRole('button',{name:'Apply changes'}).click();
  await save();assert.match(writes.at(-1).document.items[0].description,/Comfort/);
  await page.screenshot({path:path.join(output,'testimonials.png')});
  await tab('Products');await page.getByRole('button',{name:'Backhoe loaders',exact:true}).click();
  await page.getByLabel('Heading',{exact:true}).fill('BACKHOE POWER');
  await page.getByLabel('Subtitle',{exact:true}).fill('Dealer machines');
  await page.getByLabel('Description',{exact:true}).fill('Built for demanding work.');
  const oldCount=await page.locator('.content-list-item').count();
  await page.getByRole('button',{name:'Add item',exact:true}).click();popup=page.getByRole('dialog').last();
  await popup.getByLabel('Name',{exact:true}).fill('New BULL loader');
  await popup.getByLabel('Description',{exact:true}).fill('A new machine for the dealer catalogue.');
  await popup.getByLabel('Link',{exact:true}).fill('https://example.com/new-machine');
  await popup.locator('input[type=file]').setInputFiles(path.join(__dirname,'../apps/admin/public/brand/bull-machine-logo.webp'));
  await popup.getByRole('button',{name:'Apply changes'}).click();
  assert.equal(await page.locator('.content-list-item').count(),oldCount+1);
  await save();
  const newProduct=writes.at(-1).document.items.find(x=>x.name==='New BULL loader');
  assert.ok(newProduct.image);assert.equal(newProduct.category,'Backhoe loaders');
  assert.equal(newProduct.showInMenu,true);
  assert.equal(await page.locator('.product-list .item-thumbnail img').first().evaluate(el=>getComputedStyle(el).objectFit),'contain');
  await page.screenshot({path:path.join(output,'products.png')});
  await page.getByRole('button',{name:'Skid steers',exact:true}).click();
  await page.getByLabel('Heading',{exact:true}).fill('SKID STEER POWER');await save();
  await tab('Contact');assert.equal(await page.locator('.content-list-item .item-thumbnail').count(),0);
  await page.locator('.content-list-item').first().click();popup=page.getByRole('dialog').last();
  await popup.getByLabel('Label',{exact:true}).fill('Your name');
  await popup.getByRole('button',{name:'Apply changes'}).click();await save();
  await page.screenshot({path:path.join(output,'contact.png')});
  await tab('News & updates');
  await page.getByRole('button',{name:'Add item',exact:true}).click();popup=page.getByRole('dialog').last();
  await popup.getByLabel('Body',{exact:true}).fill('Latest dealer news and product announcements.');
  await popup.locator('input[type=file]').setInputFiles(path.join(__dirname,'../apps/admin/public/brand/bull-machine-logo.webp'));
  await popup.getByLabel('Title',{exact:true}).fill('Dealer news');await popup.getByRole('button',{name:'Apply changes'}).click();await save();
  await page.screenshot({path:path.join(output,'news.png')});
  await page.getByRole('button',{name:'Close popup'}).click();
  await page.getByRole('link',{name:'Dashboard',exact:true}).click();
  await page.locator('.dashboard-metrics').waitFor();await page.screenshot({path:path.join(output,'dashboard.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:5184/admin/dealers');
  await page.getByRole('button',{name:'Edit Tara Auto Hub Pvt. Ltd.'}).click();await tab('Videos & testimonials');
  await page.locator('.content-list-item').first().click();popup=page.getByRole('dialog').last();
  await popup.getByLabel('Description',{exact:true}).waitFor();
  assert.ok(await popup.evaluate(el=>el.getBoundingClientRect().width<=390));
  await popup.locator('.cms-dialog-body').evaluate(el=>{el.scrollTop=150;});
  await page.screenshot({path:path.join(output,'mobile-popup.png')});
  await popup.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Close popup'}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const web=await context.newPage();web.on('pageerror',e=>errors.push(e.message));await web.goto('http://127.0.0.1:5183/');
  await web.getByText('BACKHOE POWER',{exact:true}).waitFor();await web.getByText('SKID STEER POWER',{exact:true}).waitFor();
  assert.equal(await web.locator('meta[property="og:title"]').getAttribute('content'),'Tara machines');
  assert.ok((await web.locator('body').textContent()).includes('Comfort for every working day.'));
  assert.ok((await web.locator('body').textContent()).includes('New BULL loader'));
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({result:'passed',liveDatabase:false,checks:['responsive dealer list','removed navigation','arrow-free scrollbar styles','black/yellow palette','SEO meta output','testimonial paragraphs','nested item popup edits','new product image upload and save','both category headings','contact without image placeholders','news list popup','mobile scrolling and overflow','public website content'],apiValidation:'real validateSection on all mock saves'},null,2));
  console.log('PASS V3 admin and website checks with real API schema validation.');
 }catch(e){await page.screenshot({path:path.join(output,'failure.png')});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

