server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  add_header X-Frame-Options SAMEORIGIN always;
  client_max_body_size 11m;
  location /api/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
  location /uploads/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $http_host;
  }
  location = /admin { return 301 /admin/; }
  location /admin/ { try_files $uri $uri/ /admin/index.html; }
  location /Asset/ { try_files $uri =404; }
  location /images/ { try_files $uri =404; }
  location / { try_files $uri $uri/ /index.html; }
}
